In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df=pd.read_csv("diabetes.csv")

In [3]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [5]:
df["Glucose"].unique

<bound method Series.unique of 0      148
1       85
2      183
3       89
4      137
      ...
763    101
764    122
765    121
766    126
767     93
Name: Glucose, Length: 768, dtype: int64>

In [6]:
for col in df.columns:

IndentationError: expected an indented block (1300467820.py, line 3)

In [ ]:
sns.heatmap(df.corr(),annot=True)

In [ ]:
df.columns[0]
len(df.columns)
1!=9

In [ ]:

for index,row in df.iterrows():
    if index!=len(df.columns):
            x=df.columns[index]
            print(x)
    mean=df[x].mean()
    std=df[x].std()
    print((row[x]-mean)/std)

In [ ]:
mean=df["Glucose"].mean()
mean

In [ ]:
mo=df["BMI"].mean()
df["BMI"].median()
df['BMI'].mode()
round(mo,0),df["BMI"].median(),df['BMI'].mode()

In [ ]:
sns.histplot(df['BMI'],kde=True)

In [7]:
import scipy.stats as stats
stats.zscore(df)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.639947,0.848324,0.149641,0.907270,-0.692891,0.204013,0.468492,1.425995,1.365896
1,-0.844885,-1.123396,-0.160546,0.530902,-0.692891,-0.684422,-0.365061,-0.190672,-0.732120
2,1.233880,1.943724,-0.263941,-1.288212,-0.692891,-1.103255,0.604397,-0.105584,1.365896
3,-0.844885,-0.998208,-0.160546,0.154533,0.123302,-0.494043,-0.920763,-1.041549,-0.732120
4,-1.141852,0.504055,-1.504687,0.907270,0.765836,1.409746,5.484909,-0.020496,1.365896
...,...,...,...,...,...,...,...,...,...
763,1.827813,-0.622642,0.356432,1.722735,0.870031,0.115169,-0.908682,2.532136,-0.732120
764,-0.547919,0.034598,0.046245,0.405445,-0.692891,0.610154,-0.398282,-0.531023,-0.732120
765,0.342981,0.003301,0.149641,0.154533,0.279594,-0.735190,-0.685193,-0.275760,-0.732120
766,-0.844885,0.159787,-0.470732,-1.288212,-0.692891,-0.240205,-0.371101,1.170732,1.365896
767,-0.844885,-0.873019,0.046245,0.656358,-0.692891,-0.202129,-0.473785,-0.871374,-0.732120

In [11]:
import statistics
def Z_socre(data):
    for i in data.columns[:-1]:
        mean=round(data[i].mean(),0)
        std=data[i].std()
        mid=data[i].median()
        if mean==mid:
                Z_lower=((data[i]-mean)/std)>3
                Z_upper=((data[i]-mean)/std)<-3
                temp=data[Z_lower].index
                temp_1=data[Z_upper].index
                print(temp,temp_1)
                data.drop(temp , axis = 0,inplace=True)
                data.drop(temp_1 , axis = 0,inplace=True)

                print(data[Z_lower][i],data[Z_upper][i])
        else:
            q1 = data[i].quantile(0.25)
            q3 = data[i].quantile(0.75)
            iqr = q3 - q1 

            upper_whisker = q3 + 1.5* iqr
            lower_whisker = q1 - 1.5* iqr
            if lower_whisker < 0 :
                lower_whisker = 0 
            out_1 = data[i] >  upper_whisker 
            out_2 = data[i] <  lower_whisker

            Ser_1 = data[out_1].index
            Ser_2 = data[out_2].index
            data.drop(Ser_1 , axis = 0,inplace=True)
            data.drop(Ser_2 , axis = 0,inplace=True)

In [12]:
Z_socre(df)

Int64Index([], dtype='int64') Int64Index([], dtype='int64')
Series([], Name: BloodPressure, dtype: int64) Series([], Name: BloodPressure, dtype: int64)
Int64Index([120, 303], dtype='int64') Int64Index([], dtype='int64')
Series([], Name: BMI, dtype: float64) Series([], Name: BMI, dtype: float64)

C:\Users\dell\AppData\Local\Temp\ipykernel_12588\1831799501.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(data[Z_lower][i],data[Z_upper][i])

In [13]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
5,5,116,74,0,0,25.6,0.201,30,0
...,...,...,...,...,...,...,...,...,...
762,9,89,62,0,0,22.5,0.142,33,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0